const wordList = {
  git: [
    { word: "git init",        desc: "リポジトリを新規作成する" },
    { word: "git clone",       desc: "リモートリポジトリをローカルにコピー" },
    { word: "git status",      desc: "変更ファイルの状態を確認" },
    { word: "git add .",       desc: "全変更をステージングエリアに追加" },
    { word: "git commit",      desc: "ステージした変更をコミットとして記録" },
    { word: "git push",        desc: "ローカルコミットをリモートへ送信" },
    { word: "git pull",        desc: "リモートの変更をローカルに取得＆マージ" },
    { word: "git fetch",       desc: "リモートの変更を取得（マージはしない）" },
    { word: "git merge",       desc: "ブランチを現在のブランチに統合" },
    { word: "git rebase",      desc: "コミット履歴をきれいに並べ直す" },
    { word: "git branch",      desc: "ブランチ一覧の表示・作成" },
    { word: "git checkout",    desc: "ブランチやコミットに切り替える" },
    { word: "git switch",      desc: "ブランチを切り替える（新しい書き方）" },
    { word: "git stash",       desc: "作業中の変更を一時退避する" },
    { word: "git stash pop",   desc: "退避した変更を元に戻す" },
    { word: "git log",         desc: "コミット履歴を一覧表示" },
    { word: "git diff",        desc: "変更内容の差分を表示" },
    { word: "git reset",       desc: "コミットやステージを取り消す" },
    { word: "git revert",      desc: "コミットを打ち消す新しいコミットを作成" },
    { word: "git cherry-pick", desc: "特定のコミットだけを取り込む" },
    { word: "git tag",         desc: "コミットにタグ（バージョン名）を付ける" },
    { word: "git remote",      desc: "リモートリポジトリを管理する" },
    { word: "git blame",       desc: "各行を最後に変更したコミットを表示" },
    { word: "git show",        desc: "コミットの詳細内容を表示" },
    { word: "git reflog",      desc: "HEADの移動履歴を確認（復元に使える）" },
    { word: "git rm",          desc: "ファイルをGit管理から削除" },
    { word: "git mv",          desc: "ファイルの移動またはリネーム" },
    { word: "git bisect",      desc: "二分探索でバグを導入したコミットを特定" },
    { word: "git submodule",   desc: "別リポジトリをサブモジュールとして管理" },
    { word: "git worktree",    desc: "1リポジトリで複数のワーキングツリーを使う" },
  ],
  linux: [
    { word: "ls -la",       desc: "隠しファイル含む詳細一覧を表示" },
    { word: "cd ..",        desc: "1つ上のディレクトリに移動" },
    { word: "pwd",          desc: "現在の作業ディレクトリのパスを表示" },
    { word: "mkdir -p",     desc: "親ディレクトリも含めて一括作成" },
    { word: "rm -rf",       desc: "ディレクトリを中身ごと強制削除" },
    { word: "cp -r",        desc: "ディレクトリを再帰的にコピー" },
    { word: "mv",           desc: "ファイルの移動またはリネーム" },
    { word: "touch",        desc: "空ファイルを作成 / タイムスタンプ更新" },
    { word: "cat",          desc: "ファイルの中身を標準出力に表示" },
    { word: "less",         desc: "ファイルをスクロールしながら閲覧" },
    { word: "grep -r",      desc: "ディレクトリを再帰的に文字列検索" },
    { word: "find . -name", desc: "ファイル名でファイルを検索" },
    { word: "chmod 755",    desc: "ファイルのアクセス権限を変更" },
    { word: "chown",        desc: "ファイルの所有者を変更" },
    { word: "ln -s",        desc: "シンボリックリンク（ショートカット）を作成" },
    { word: "ps aux",       desc: "実行中の全プロセスを一覧表示" },
    { word: "kill -9",      desc: "プロセスを強制終了する" },
    { word: "top",          desc: "CPU・メモリ使用状況をリアルタイム表示" },
    { word: "df -h",        desc: "ディスクの使用量を人間が読める形で表示" },
    { word: "du -sh",       desc: "ディレクトリの合計サイズを表示" },
    { word: "tar -xzvf",    desc: ".tar.gz ファイルを展開する" },
    { word: "zip",          desc: "ファイルをzip圧縮する" },
    { word: "unzip",        desc: "zipファイルを展開する" },
    { word: "ssh",          desc: "リモートサーバーに暗号化接続する" },
    { word: "scp",          desc: "SSH経由でファイルをコピー転送" },
    { word: "curl",         desc: "URLからデータを取得 / APIを叩く" },
    { word: "wget",         desc: "URLからファイルをダウンロード" },
    { word: "ping",         desc: "ホストへの疎通確認" },
    { word: "netstat",      desc: "ネットワーク接続・ポートの状態を確認" },
    { word: "sudo",         desc: "管理者権限でコマンドを実行" },
  ],
  java: [
    { word: "public static void main", desc: "Javaプログラムのエントリーポイント" },
    { word: "System.out.println",      desc: "標準出力に1行表示する" },
    { word: "String[] args",           desc: "コマンドライン引数を受け取る配列" },
    { word: "new ArrayList",           desc: "動的配列を生成する" },
    { word: "new HashMap",             desc: "キー・値のペアを管理するマップを生成" },
    { word: "interface",               desc: "実装すべきメソッドの契約を定義" },
    { word: "implements",              desc: "インターフェースを実装することを宣言" },
    { word: "extends",                 desc: "クラスを継承する" },
    { word: "abstract class",          desc: "直接インスタンス化できない抽象クラス" },
    { word: "try",                     desc: "例外が発生するかもしれない処理を囲む" },
    { word: "catch",                   desc: "tryで発生した例外を捕まえて処理" },
    { word: "finally",                 desc: "例外の有無に関わらず必ず実行されるブロック" },
    { word: "throws Exception",        desc: "このメソッドは例外を投げる可能性があると宣言" },
    { word: "NullPointerException",    desc: "nullのオブジェクトを操作したときのエラー" },
    { word: "StringBuilder",           desc: "文字列を効率よく連結するためのクラス" },
    { word: "for (int i = 0",          desc: "カウンタ変数を使った基本のforループ" },
    { word: "while (true)",            desc: "条件が常に真の無限ループ" },
    { word: "instanceof",              desc: "オブジェクトが特定クラスの型か確認" },
    { word: "override",                desc: "親クラスのメソッドを子クラスで上書き" },
    { word: "static final",            desc: "定数を定義するキーワード" },
    { word: "private",                 desc: "そのクラス内からしかアクセスできない" },
    { word: "protected",               desc: "同一パッケージ・サブクラスからアクセス可" },
    { word: "synchronized",            desc: "マルチスレッドで同時アクセスを防ぐ" },
    { word: "stream()",                desc: "コレクションをStream APIで処理するために変換" },
    { word: "filter()",                desc: "Stream内の要素を条件で絞り込む" },
    { word: "map()",                   desc: "Stream内の各要素を別の値に変換" },
    { word: "collect()",               desc: "Streamの結果をリストなどに変換して収集" },
    { word: "Optional",                desc: "nullかもしれない値を安全に扱うラッパー" },
    { word: "Arrays.sort()",           desc: "配列を昇順にソートする" },
    { word: "Collections.sort()",      desc: "リストを昇順にソートする" },
  ],
  sql: [
    { word: "SELECT * FROM",  desc: "テーブルから全列を取得する" },
    { word: "WHERE",          desc: "取得する行を条件で絞り込む" },
    { word: "ORDER BY",       desc: "結果を指定カラムで並び替える" },
    { word: "GROUP BY",       desc: "指定カラムの値でグループ化する" },
    { word: "HAVING",         desc: "GROUP BY後の集計結果に条件を付ける" },
    { word: "INNER JOIN",     desc: "両テーブルに一致する行だけ結合" },
    { word: "LEFT JOIN",      desc: "左テーブル全行＋右の一致行を結合" },
    { word: "RIGHT JOIN",     desc: "右テーブル全行＋左の一致行を結合" },
    { word: "ON",             desc: "JOINの結合条件を指定する" },
    { word: "AS",             desc: "カラムやテーブルに別名をつける" },
    { word: "INSERT INTO",    desc: "テーブルに新しい行を追加する" },
    { word: "VALUES",         desc: "INSERT時に挿入する値を指定" },
    { word: "UPDATE",         desc: "既存の行のデータを更新する" },
    { word: "SET",            desc: "UPDATEで変更するカラムと値を指定" },
    { word: "DELETE FROM",    desc: "テーブルから条件に合う行を削除" },
    { word: "CREATE TABLE",   desc: "新しいテーブルを作成する" },
    { word: "ALTER TABLE",    desc: "既存テーブルの構造を変更する" },
    { word: "DROP TABLE",     desc: "テーブルをデータごと完全削除" },
    { word: "PRIMARY KEY",    desc: "行を一意に識別するキーを設定" },
    { word: "FOREIGN KEY",    desc: "他テーブルのPKを参照する外部キー" },
    { word: "NOT NULL",       desc: "NULLを許可しない制約" },
    { word: "UNIQUE",         desc: "同じ値を重複させない制約" },
    { word: "COUNT(*)",       desc: "行数を数える集計関数" },
    { word: "SUM()",          desc: "数値カラムの合計を求める" },
    { word: "AVG()",          desc: "数値カラムの平均を求める" },
    { word: "MAX()",          desc: "カラムの最大値を取得" },
    { word: "MIN()",          desc: "カラムの最小値を取得" },
    { word: "DISTINCT",       desc: "重複を除いた一意の値を取得" },
    { word: "LIMIT",          desc: "取得件数の上限を指定" },
    { word: "LIKE",           desc: "パターンマッチングで文字列を検索" },
  ],
  command: [
    { word: "npm install",        desc: "package.jsonの依存パッケージをインストール" },
    { word: "npm run build",      desc: "プロジェクトをプロダクション向けにビルド" },
    { word: "npm run dev",        desc: "開発用サーバーを起動する" },
    { word: "npm test",           desc: "テストスイートを実行する" },
    { word: "npx",                desc: "パッケージをインストールせずに実行" },
    { word: "docker run",         desc: "Dockerイメージからコンテナを起動" },
    { word: "docker ps",          desc: "起動中のコンテナを一覧表示" },
    { word: "docker build",       desc: "DockerfileからDockerイメージを作成" },
    { word: "docker exec -it",    desc: "実行中のコンテナ内でコマンドを実行" },
    { word: "docker-compose up",  desc: "複数コンテナをまとめて起動する" },
  ],
  programming: [
    { word: "async",            desc: "非同期関数を定義するキーワード" },
    { word: "await",            desc: "Promiseの結果が返るまで処理を待つ" },
    { word: "console.log",      desc: "ブラウザのコンソールに値を出力" },
    { word: "Promise",          desc: "非同期処理の完了・失敗を扱うオブジェクト" },
    { word: "forEach",          desc: "配列の各要素に対して処理を繰り返す" },
    { word: "map()",            desc: "配列の各要素を変換した新しい配列を返す" },
    { word: "filter()",         desc: "条件を満たす要素だけの配列を返す" },
    { word: "reduce()",         desc: "配列を1つの値に集約する" },
    { word: "fetch",            desc: "HTTPリクエストを送ってデータを取得" },
    { word: "querySelector",    desc: "CSSセレクタでDOM要素を1つ取得" },
    { word: "addEventListener", desc: "要素にイベントリスナーを登録する" },
    { word: "try",              desc: "例外が発生するかもしれない処理を囲む" },
    { word: "catch",            desc: "tryで発生したエラーを受け取って処理" },
    { word: "JSON.parse()",     desc: "JSON文字列をオブジェクトに変換" },
    { word: "JSON.stringify()", desc: "オブジェクトをJSON文字列に変換" },
  ],
};
